# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build & Push Docker Images

on:
  push:
    branches: 
      - dev_docker

# how to set variables for the job
env:
  DOCKERHUB_USERNAME: infiloop

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: share/docker
          file: ./Dockerfile
          push: false
          target: core
          tags: infispiel/darshan_util_dxtthread:latest

      - name: Build and push development Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: share/docker
          file: ./Dockerfile
          push: false
          tags: infispiel/darshan_util_dxtthread_dev:latest
